{{- if gt (len .Values.secretEnv) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traffic-manager.fullname" . }}
  labels:
    {{- include "traffic-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
