apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - route-resolution-service.yaml
  - route-management-service.yaml
  - cache-invalidation-consumer.yaml
  - cache-warming-consumer.yaml
  - audit-consumer.yaml
