apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: route-resolution-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamtahmad1/traffic-manager.git
    targetRevision: main
    path: argocd/charts/route-resolution-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traffic-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
